#!/usr/bin/env python3
"""
Build the NEW hospital navigation data from v3_hospital_layout.py (no V2.6 / old-V3 data is used):
  V3/data/v3_hospital_navigation_memory.db   fresh topology DB (nodes, edges, route segments, empty history)
  V3/config/v3_hospital_semantic_map.yaml     destinations + physical signs (read by the V3 detection node)
  V3/config/logistics_locations.yaml          mission locations (read by the V3 mission manager)
Usage: build_v3_hospital_topology.py [--keep-history]   (default re-creates the DB from scratch)
"""
import math
import os
import sqlite3
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
V3 = os.path.dirname(HERE)
PROJECT = os.path.dirname(V3)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(PROJECT, "ros2_ws", "src", "autonomous_robot_navigation"))
import v3_hospital_layout as L  # noqa: E402
from v3_hospital_additions import sign_texture  # noqa: E402

DB = os.path.join(V3, "data", "v3_hospital_navigation_memory.db")
SEM = os.path.join(V3, "config", "v3_hospital_semantic_map.yaml")
LOC = os.path.join(V3, "config", "logistics_locations.yaml")
NARROW = {"storage_door", "lab_door", "ward_west_door", "ward_east_door"}  # ~0.9-1.4 m doorways


def build_db():
    if os.path.exists(DB) and "--keep-history" in sys.argv:
        print(f"kept: {DB}")
        return
    if os.path.exists(DB):
        os.remove(DB)
    from autonomous_robot_navigation.navigation_memory import NavigationMemory
    NavigationMemory(DB)  # creates the schema (and seeds its built-in topology, removed below)
    pos = {n[0]: (n[2], n[3]) for n in L.NODES}
    with sqlite3.connect(DB) as c:
        tables = [r[0] for r in c.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")]
        for t in tables:
            c.execute(f"DELETE FROM {t}")
        c.executemany("INSERT INTO nodes (id, name, x, y, theta, node_type, semantic_label) VALUES (?,?,?,?,?,?,?)", L.NODES)
        for u, v in L.EDGES:
            d = math.dist(pos[u], pos[v])
            narrow = int(u in NARROW or v in NARROW)
            for a, b in ((u, v), (v, u)):
                c.execute("INSERT INTO edges (from_node, to_node, distance, cost, traversal_count, is_blocked, is_dead_end) "
                          "VALUES (?,?,?,?,0,0,0)", (a, b, d, d))
                c.execute("INSERT INTO route_segments (from_node, to_node, distance, traversal_count, success_count, failure_count, "
                          "avg_travel_time, avg_clearance, obstacle_encounter_count, replan_count, is_narrow, is_dead_end, "
                          "reliability_score, last_traversed) VALUES (?,?,?,0,0,0,0.0,0.5,0,0,?,0,1.0,0.0)", (a, b, d, narrow))
        n = c.execute("SELECT count(*) FROM nodes").fetchone()[0]
        e = c.execute("SELECT count(*) FROM edges").fetchone()[0]
    print(f"topology DB: {DB} ({n} nodes, {e} directed edges, empty history)")


def build_semantic_map():
    nodes = {n[0]: n for n in L.NODES}
    dests = {}
    for nid, name, x, y, th, typ, label in L.NODES:
        if typ == "destination":
            dests[nid] = {"name": name, "category": label.lower(), "node_id": nid, "x": x, "y": y, "yaw": th}
    signs = {}
    for sid, junction, dest, text, direction, x, y, z, yaw, appr in L.SIGNS:
        fname, _ = sign_texture(text, direction)
        signs[sid] = {"id": sid, "junction": junction, "destination": dest, "direction": direction, "text": text,
                      "texture_file": fname,
                      "wall_attachment": {"x": x, "y": y, "z": z, "yaw": round(yaw, 5)},
                      "approaching_from": appr, "branch_node": junction, "confidence_prior": 0.95}
        assert junction in nodes and dest in nodes
    doc = {"version": "3.1", "facility_name": "V3 Hospital (AWS RoboMaker Hospital World floor plan)",
           "world": "V3/worlds/v3_hospital_world.sdf", "map": "V3/maps/v3_hospital_map.yaml",
           "destinations": dests, "signs": signs}
    with open(SEM, "w") as f:
        f.write("# Generated by V3/scripts/build_v3_hospital_topology.py from v3_hospital_layout.py. Do not edit.\n")
        yaml.safe_dump(doc, f, sort_keys=False)
    print(f"semantic map: {SEM} ({len(dests)} destinations, {len(signs)} signs)")


def build_locations():
    nodes = {n[0]: n for n in L.NODES}
    locs = {}
    for key, v in L.LOGISTICS.items():
        n = nodes[v["node"]]
        locs[key] = {"node": v["node"], "label": v["label"], "x": n[2], "y": n[3]}
        if "marker_class" in v:
            locs[key]["marker_class"] = v["marker_class"]
    doc = {"locations": locs,
           "mission": {"default_source": "collection_point", "default_destination": "laboratory",
                       "payload": "blood_sample", "collect_dwell_s": 3.0, "deliver_dwell_s": 3.0,
                       "leg_timeout_s": 300.0, "arrival_tolerance_m": 0.8, "marker_window_s": 15.0}}
    with open(LOC, "w") as f:
        f.write("# V3 NEW hospital logistics locations -> topology nodes of V3/data/v3_hospital_navigation_memory.db\n"
                "# Generated by V3/scripts/build_v3_hospital_topology.py from v3_hospital_layout.py.\n"
                "# collection_point: West Ward aisle (sample pickup at the bedside table); laboratory: NE laboratory test point.\n")
        yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=None)
    print(f"logistics locations: {LOC}")


if __name__ == "__main__":
    build_db()
    build_semantic_map()
    build_locations()
