#!/usr/bin/env python3
"""
Build the V3 hospital world from the AWS RoboMaker Hospital World (MIT-0) and its OpenRobotics Gazebo Fuel
furniture (CC-BY 4.0). Source record: V3/V3_NEW_HOSPITAL_SOURCE.md.

Inputs (fetched once, see V3_NEW_HOSPITAL_SOURCE.md):
  V3/third_party/aws-robomaker-hospital-world   (git clone, branch ros2, commit 7161eb8)
  V3/third_party/fuel_cache                     (GZ_FUEL_CACHE_PATH used for `gz fuel download`)
Outputs:
  V3/hospital/models/<model>/                   vendored models (AWS + Fuel), Gazebo Sim 10 ready
  V3/worlds/v3_hospital_world.sdf               the runtime world

Conversion (Gazebo Classic world -> Gazebo Sim 10.5):
  - world renamed to 'realistic_facility_world' (the bridge/spawn world name the V3 runtime uses)
  - Gazebo Sim system plugins (physics, user commands, scene broadcaster, sensors/ogre2, imu)
  - Classic <physics> 1 kHz ODE replaced by the V3 200 Hz step
  - each `<model name=N><include>uri,pose</include></model>` wrapper flattened to
    `<include><name>N</name><uri/><pose/></include>`
  - Fuel mesh URIs rewritten to relative paths (offline), Fuel props forced static
  - the building is used unchanged (walls, floor, nurses station, curtains, elevators, signs, décor);
    the ceiling is left out so the GUI shows the floor plan from above (as in the AWS world file)
  - V3 additions (separate section): lights, logistics plaques, room signs, dynamic traffic models
"""
import os
import re
import shutil
import sys

V3 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AWS = os.path.join(V3, "third_party", "aws-robomaker-hospital-world")
CACHE = os.path.join(V3, "third_party", "fuel_cache", "fuel.gazebosim.org", "openrobotics", "models")
OUT_MODELS = os.path.join(V3, "hospital", "models")
OUT_WORLD = os.path.join(V3, "worlds", "v3_hospital_world.sdf")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from v3_hospital_additions import additions_sdf  # noqa: E402


URI_NAMES = {u.lower(): u for u in re.findall(r"model://([^<\s/]+)",
                                               open(os.path.join(AWS, "worlds", "hospital.world")).read())}


def vendor_fuel():
    rows = []
    for d in sorted(os.listdir(CACHE)):
        versions = sorted((v for v in os.listdir(os.path.join(CACHE, d)) if v.isdigit()), key=int)
        src = os.path.join(CACHE, d, versions[-1])
        cfg = open(os.path.join(src, "model.config")).read()
        name = re.search(r"<name>\s*([^<]+?)\s*</name>", cfg).group(1)
        name = URI_NAMES.get(d.lower(), name.replace(" ", ""))
        dst = os.path.join(OUT_MODELS, name)
        if os.path.exists(dst):
            shutil.rmtree(dst)
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns("*.zip", "thumbnails"))
        p = os.path.join(dst, "model.sdf")
        t = open(p).read()
        t = re.sub(r"https://fuel\.gazebosim\.org/1\.0/openrobotics/models/[^/]+/\d+/files/", "", t, flags=re.I)
        if "<static>" in t:
            t = re.sub(r"<static>\s*\w+\s*</static>", "<static>true</static>", t)
        else:
            t = re.sub(r"(<model name=[\"'][^\"']*[\"']>)", r"\1\n    <static>true</static>", t, count=1)
        open(p, "w").write(t)
        rows.append((name, versions[-1], "remote-uri" if re.search(r"https?://", t) else "ok"))
    return rows


def vendor_aws():
    for name in os.listdir(os.path.join(AWS, "models")):
        dst = os.path.join(OUT_MODELS, name)
        if os.path.exists(dst):
            shutil.rmtree(dst)
        shutil.copytree(os.path.join(AWS, "models", name), dst)
        for root, _d, files in os.walk(dst):  # portrait photos: upstream path is relative to the repo root
            for f in files:
                if f.lower().endswith(".dae"):
                    fp = os.path.join(root, f)
                    s = open(fp, errors="ignore").read()
                    if "../../../../photos/" in s:
                        open(fp, "w").write(s.replace("../../../../photos/", "../../../photos/"))
    # The robot drives on the flat ground plane, not on the AWS floor triangle mesh: cylinder wheels on the mesh
    # slip (measured: wheel odometry 1.52x the true distance -> AMCL drift of metres along the corridors).
    floor = os.path.join(OUT_MODELS, "aws_robomaker_hospital_floor_01_floor", "model.sdf")
    s = open(floor).read()
    open(floor, "w").write(re.sub(r"<collision name=\"collision\">.*?</collision>", "", s, flags=re.S))
    photos = os.path.join(os.path.dirname(OUT_MODELS), "photos")
    if os.path.exists(photos):
        shutil.rmtree(photos)
    shutil.copytree(os.path.join(AWS, "photos"), photos)


HEADER = """<?xml version='1.0'?>
<!-- Generated by V3/scripts/build_aws_hospital_world.py from the AWS RoboMaker Hospital World (MIT-0)
     and OpenRobotics Gazebo Fuel models (CC-BY 4.0). Do not edit by hand. -->
<sdf version="1.9">
  <world name="realistic_facility_world">
    <gravity>0 0 -9.8</gravity>
    <physics name="default_physics" default="true" type="ode">
      <max_step_size>0.005</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>200</real_time_update_rate>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics" />
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands" />
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster" />
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu" />
    <scene>
      <ambient>0.7 0.7 0.7 1</ambient>
      <background>0.75 0.8 0.85 1</background>
      <shadows>false</shadows>
      <grid>false</grid>
    </scene>
    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 30 0 0 0</pose>
      <diffuse>0.85 0.85 0.85 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.3 0.2 -0.9</direction>
    </light>
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision"><geometry><plane><normal>0 0 1</normal><size>200 200</size></plane></geometry></collision>
      </link>
      <pose>0 0 0 0 0 0</pose>
    </model>
"""


# The three upstream props that had fallen through the floor are restored; the trolley bed (upstream pose in the
# middle of the east corridor) is parked lengthwise along the corridor wall.
FALLEN_PROP_POSES = {"TrolleyBed_1": "5.85 -5.0 0 0 0 1.5708"}
# Warehouse clutter in the NE room is replaced by the V3 laboratory furnishing (v3_hospital_additions.py).
DROPPED = {"aws_robomaker_warehouse_ClutteringA_01_1"}


def convert_world():
    src = open(os.path.join(AWS, "worlds", "hospital.world")).read()
    blocks = re.findall(r"<model name=\"([^\"]+)\">\s*<include>(.*?)</include>\s*</model>", src, flags=re.S)
    out, skipped = [], []
    for name, inner in blocks:
        uri = re.search(r"<uri>([^<]+)</uri>", inner).group(1).strip()
        pose = re.search(r"<pose>([^<]+)</pose>", inner)
        if "ceiling" in uri:
            skipped.append(name)
            continue
        pv = (pose.group(1).split() if pose else ["0"] * 6)
        if abs(float(pv[2])) > 10:  # upstream AWS world bug: a few props saved at z=-7.6e8 (fell through)
            pv[2] = "0"
        if name in FALLEN_PROP_POSES:  # restored props re-placed where they do not block a corridor
            pv = FALLEN_PROP_POSES[name].split()
        if name in DROPPED:
            skipped.append(name)
            continue
        out.append(f"    <include>\n      <name>{name}</name>\n      <uri>{uri}</uri>\n"
                   f"      <pose>{' '.join(pv)}</pose>\n      <static>true</static>\n    </include>")
    return out, skipped, len(blocks)


def main():
    os.makedirs(OUT_MODELS, exist_ok=True)
    fuel = vendor_fuel()
    vendor_aws()
    incs, skipped, n = convert_world()
    world = HEADER + "\n".join(incs) + "\n" + additions_sdf() + "\n  </world>\n</sdf>\n"
    open(OUT_WORLD, "w").write(world)
    with open(os.path.join(OUT_MODELS, "ATTRIBUTION.md"), "w") as f:
        f.write("# V3 hospital model attribution\n\n"
                "- `aws_robomaker_*` models: AWS RoboMaker Hospital World, https://github.com/aws-robotics/aws-robomaker-hospital-world "
                "(branch ros2, commit 7161eb8448f5cba6a469da7a79ae5d660b0b7f58), MIT-0 license.\n"
                "- All other models: OpenRobotics collection on Gazebo Fuel, CC-BY 4.0 "
                "(https://creativecommons.org/licenses/by/4.0/). Modifications: mesh URIs made relative, forced static.\n\n"
                "| Fuel model | URL | Version |\n|---|---|---|\n")
        for name, ver, _ in fuel:
            f.write(f"| {name} | https://fuel.gazebosim.org/1.0/OpenRobotics/models/{name} | {ver} |\n")
    bad = [r for r in fuel if r[2] != "ok"]
    print(f"fuel models: {len(fuel)} (remote URIs left: {len(bad)}); AWS models copied; "
          f"world includes: {len(incs)} of {n} (skipped ceiling: {skipped}) -> {OUT_WORLD}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
