#!/usr/bin/env python3
"""Render the Phase 2 result tables (markdown) directly from the evidence JSON files, so no number in
the reports is transcribed by hand. Output: V3/docs/phase2_result_tables.md"""
import json
import os

V3_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EV = os.path.join(V3_ROOT, "docs", "evidence")
ev = json.load(open(os.path.join(EV, "phase2_eval", "evaluation.json")))
bench = json.load(open(os.path.join(EV, "phase2_inference_benchmark.json")))
fus = json.load(open(os.path.join(EV, "phase2_fusion", "fusion_validation.json")))
ds = json.load(open(os.path.join(V3_ROOT, "datasets", "v3_hospital_cv", "dataset_validation.json")))
MODELS = [("v25", "V2.5 @0.35"), ("v25_deployed", "V2.5 @deployed thr."), ("v3_from_v25", "V3 (init V2.5) @0.35"),
          ("v3_from_coco", "V3 (init COCO) @0.35")]
NAMES = ["person", "hospital_bed", "cart", "wheelchair", "iv_stand", "surgical_trolley", "directional_sign",
         "collection_point_marker", "lab_test_point_marker"]
TARGET = {"A_hospital_beds": "hospital_bed", "B_bed_vs_lab_bench": "hospital_bed", "C_bed_vs_reception_desk": "hospital_bed",
          "D_chair_vs_cart": "cart", "E_trolley_vs_forklift_cart": "surgical_trolley", "F_wheelchair": "wheelchair",
          "G_iv_stand": "iv_stand", "H_person": "person", "I_empty_hallway": None, "J_cluttered_corridor": None}
f = lambda v: "–" if v is None else (f"{v:.3f}" if isinstance(v, float) else str(v))
L = ["# Phase 2 result tables (generated by V3/training/make_phase2_tables.py)", ""]

L += ["## Dataset", "", "| Set | Images | Empty | Instances per class | Dropped (small / occluded) | Label verification |", "|---|---|---|---|---|---|"]
for grp in ("splits", "subsets"):
    for k, v in ds[grp].items():
        inst = ", ".join(f"{n}:{v['instances'].get(n, 0)}" for n in NAMES if v["instances"].get(n))
        dr = v["dropped_instances"]
        L.append(f"| {k} | {v['images']} | {v['empty_images']} | {inst} | {dr.get('dropped_small', 0)} / {dr.get('dropped_occluded', 0)} | {v['label_verification']} |")

L += ["", "## Canonical V3 test split — aggregate", "", "| Model | mAP50 | mAP50-95 | Precision | Recall | TP | FP (in-taxonomy) | FP (out-of-taxonomy) | FN | FP / image |", "|---|---|---|---|---|---|---|---|---|---|"]
for t, name in MODELS:
    r = ev["sets"]["test_canonical"][t]
    T = r["total"]
    L.append(f"| {name} | {f(r['mAP50'])} | {f(r['mAP50_95'])} | {f(T['precision'])} | {f(T['recall'])} | {T['TP']} | {T['FP_in_taxonomy']} | {T['FP_out_of_taxonomy']} | {T['FN']} | {f(T['FP_per_image'])} |")
L += ["", "mAP here is the evaluator's all-point AP over classes present in the set (V2.5 scores 0 on classes it does not have)."]
for t in ("v3_from_v25", "v3_from_coco"):
    u = ev["models"][t]["ultralytics_test"]
    L += [f"", f"ultralytics `val` ({t}, test split): mAP50 {u['mAP50']}, mAP50-95 {u['mAP50_95']}, P {u['precision']}, R {u['recall']}; "
          f"confusion matrix: `{os.path.relpath(u['confusion_matrix_png'], V3_ROOT)}`"]

L += ["", "## Canonical V3 test split — per class", "", "| Class | GT | V2.5 deployed P / R | V3 (init V2.5) P / R | V3 AP50 | V3 AP50-95 | ultralytics AP50 / AP50-95 |", "|---|---|---|---|---|---|---|"]
u = ev["models"]["v3_from_v25"]["ultralytics_test"]
for n in NAMES:
    a = ev["sets"]["test_canonical"]["v25_deployed"]["per_class"].get(n, {})
    b = ev["sets"]["test_canonical"]["v3_from_v25"]["per_class"].get(n, {})
    L.append(f"| {n} | {b.get('GT', '–')} | {f(a.get('precision'))} / {f(a.get('recall'))} | {f(b.get('precision'))} / {f(b.get('recall'))} | "
             f"{f(ev['sets']['test_canonical']['v3_from_v25']['AP50'].get(n))} | {f(ev['sets']['test_canonical']['v3_from_v25']['AP50_95'].get(n))} | "
             f"{f(u['per_class_AP50'].get(n))} / {f(u['per_class_AP50_95'].get(n))} |")

L += ["", "## Challenge subsets — target class", "", "| Subset | Target | GT | V2.5 deployed TP / FP / FN (P, R) | V3 (init V2.5) TP / FP / FN (P, R) | V3 (init COCO) P, R |", "|---|---|---|---|---|---|"]
for s, c in TARGET.items():
    if c is None:
        continue
    row = [s, c]
    a = ev["sets"][s]["v25_deployed"]["per_class"].get(c, {})
    b = ev["sets"][s]["v3_from_v25"]["per_class"].get(c, {})
    cc = ev["sets"][s]["v3_from_coco"]["per_class"].get(c, {})
    L.append(f"| {s} | {c} | {b.get('GT')} | {a.get('TP', 0)} / {a.get('FP', 0)} / {a.get('FN', 0)} ({f(a.get('precision'))}, {f(a.get('recall'))}) | "
             f"{b.get('TP', 0)} / {b.get('FP', 0)} / {b.get('FN', 0)} ({f(b.get('precision'))}, {f(b.get('recall'))}) | {f(cc.get('precision'))}, {f(cc.get('recall'))} |")

L += ["", "## Challenge subsets — all classes, all false positives", "", "| Subset | Model | Precision | Recall | TP | FP total | FN | FP / image | images with FP |", "|---|---|---|---|---|---|---|---|---|"]
for s in TARGET:
    for t, name in MODELS:
        T = ev["sets"][s][t]["total"]
        L.append(f"| {s} | {name} | {f(T['precision'])} | {f(T['recall'])} | {T['TP']} | {T['FP_total']} | {T['FN']} | {f(T['FP_per_image'])} | {T['images_with_FP']} |")

L += ["", "## Hard-negative FP attribution (top 6 per subset)", ""]
for s in ("B_bed_vs_lab_bench", "C_bed_vs_reception_desk", "D_chair_vs_cart", "E_trolley_vs_forklift_cart", "G_iv_stand",
          "I_empty_hallway", "J_cluttered_corridor", "test_canonical"):
    for t in ("v25_deployed", "v3_from_v25"):
        top = list(ev["sets"][s][t]["FP_attribution"].items())[:6]
        L.append(f"- **{s}**, {t}: " + (", ".join(f"{k} ×{v}" for k, v in top) if top else "no false positives"))
L += ["", "`X on GT:Y` = prediction of class X on a labelled object of class Y (for X = Y: duplicate / IoU < 0.5); "
      "`neg:` = unlabelled movable prop; `struct:` = fixed furniture / pillar / wall; `background` = none of these."]

L += ["", "## Inference benchmark", "", f"GPU: {bench['gpu']} · torch {bench['torch']} · {bench['note']}", "",
      "| Model | Params (M) | Pre / Inference / Post (ms) | End-to-end mean / p50 / p95 (ms) | FPS | torch peak alloc / reserved (MiB) | process VRAM nvidia-smi (MiB) |",
      "|---|---|---|---|---|---|---|"]
for t, r in bench["results"].items():
    l = r["latency_ms"]
    L.append(f"| {t} | {r['params_M']} | {l['preprocess_mean']} / {l['inference_mean']} / {l['postprocess_mean']} | {l['end_to_end_mean']} / {l['end_to_end_p50']} / {l['end_to_end_p95']} | "
             f"{r['fps_end_to_end']} | {r['torch_peak_allocated_mib']} / {r['torch_peak_reserved_mib']} | {r['process_vram_mib_nvidia_smi']} |")

L += ["", "## Camera-LiDAR fusion (V2.6 association) vs Gazebo ground truth", "",
      f"{fus['frames']} frames, conf {fus['conf']}; detections not matched to GT (excluded): {fus['detections_not_matched_to_gt']}", "",
      "| Boxes | Associations | Not in LiDAR plane | Measurable | Range OK (±0.30 m) | Fused point ON object (≤0.25 m) | OK range error mean / median / p95 (m) |", "|---|---|---|---|---|---|---|"]
for k, name in (("detected_objects", "V3 detections"), ("oracle_gt_boxes", "GT boxes (oracle)")):
    v = fus[k]
    e = v.get("ok_abs_range_error_m", {})
    L.append(f"| {name} | {v['n']} | {v['outcomes'].get('NOT_IN_LIDAR_PLANE', 0)} | {v['measurable']} | {f(v['ok_rate_of_measurable'])} | "
             f"{f(v['on_object_rate_of_measurable'])} | {e.get('mean')} / {e.get('median')} / {e.get('p95')} |")
v = fus["detected_objects"]
L += ["", "ON-object rate by true range (V3 detections): " + ", ".join(f"{k}: {x}" for k, x in v["on_object_rate_by_true_range"].items()), "",
      "Per class (V3 detections): " + "; ".join(f"{c}: {d}" for c, d in v["per_class_association"].items())]
out = os.path.join(V3_ROOT, "docs", "phase2_result_tables.md")
open(out, "w").write("\n".join(L) + "\n")
print(out)
